USE SUCOS;

ALTER TABLE TBCLIENTE ADD primary key (CPF);

ALTER TABLE tbcliente ADD COLUMN (DATA_NASCIMENTO DATE);

INSERT INTO TBCLIENTE (
CPF, NOME, ENDERECO, ENDERECO2, BAIRRO, CIDADE, ESTADO, CEP, IDADE, SEXO, LIMITE_CREDITO, 
VOLUME_COMPRA, PRIMEIRA_COMPRA, DATA_NASCIMENTO)
VALUES('890809890', 'jOÃO DA SILVA', 'RUA PROJETADA', '', 'VILA ROMA', 'CARATINGA', 'AMAZONAS',
'222', 30, 'M', 10000.00, 2000, 0, '1989-10-05');

SELECT * FROM tbcliente;

