SELECT * FROM TBCLIENTE where idade >= 22;

SELECT * FROM TBCLIENTE where DATA_NASCIMENTO = '1995-01-13';

SELECT * FROM TBCLIENTE where DATA_NASCIMENTO > '1995-01-13';

SELECT * FROM TBCLIENTE WHERE YEAR(DATA_NASCIMENTO) > 1995;




